// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Appointment Types
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const APPOINTMENT_ERROR = 'APPOINTMENT_ERROR';
export const CLEAR_APPOINTMENTS = 'CLEAR_APPOINTMENTS';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const FILTER_APPOINTMENTS = 'FILTER_APPOINTMENTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

// Notification Types
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const MARK_READ = 'MARK_READ';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const SEND_REMINDER = 'SEND_REMINDER';
export const SEND_CONFIRMATION = 'SEND_CONFIRMATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
